# Generated by Django 4.0.6 on 2022-07-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_the_cart_quentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.FloatField(verbose_name='Postal code')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('sity', models.CharField(max_length=255, verbose_name='Sity')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('num_home', models.CharField(max_length=255, verbose_name='Number home')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
