# Generated by Django 4.0.6 on 2022-12-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_bookinorder_order_bookinorder_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
