# Generated by Django 4.0.6 on 2023-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обрабатывается'), ('sent', 'Отправлен'), ('delivered', 'Доставлен')], default='processed', max_length=10, verbose_name='Статус'),
        ),
    ]
