# Generated by Django 4.0.6 on 2023-01-19 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_book_is_publishe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0007_points_of_issue_adress_delete_user_adress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.points_of_issue_adress', verbose_name='Адресс доставки'),
        ),
        migrations.AlterField(
            model_name='bookinorder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='bookinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='bookinorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество книг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(blank=True, through='cart.BookInOrder', to='main.book', verbose_name='Книги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Покупатель', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='points_of_issue_adress',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='points_of_issue_adress',
            name='num_home',
            field=models.CharField(max_length=255, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='points_of_issue_adress',
            name='sity',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='points_of_issue_adress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='the_cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='the_cart',
            name='quentity',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='the_cart',
            name='title_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Книга'),
        ),
    ]
