# Generated by Django 4.0.6 on 2022-07-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author_of_the_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the author')),
                ('photo', models.ImageField(upload_to='photo/author/%Y/%m/%d/', verbose_name='Book photo')),
                ('description', models.TextField(blank=True, verbose_name='Book description')),
            ],
        ),
        migrations.CreateModel(
            name='genre_of_the_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title category')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book name')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='isbn')),
                ('photo', models.ImageField(upload_to='photo/book/%Y/%m/%d/', verbose_name='Book photo')),
                ('description', models.TextField(blank=True, verbose_name='Book description')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of offering for sale')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publisher')),
                ('price', models.FloatField(verbose_name='Price')),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.author_of_the_book', verbose_name='Author')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre_of_the_book', verbose_name='Genre of the book')),
            ],
        ),
    ]
