# Generated by Django 4.0.6 on 2022-11-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_book',
            old_name='news',
            new_name='book',
        ),
    ]
