# Generated by Django 4.0.6 on 2022-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_news_comment_book_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment_book',
        ),
    ]
