# Generated by Django 4.0.6 on 2022-11-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_delete_comment_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('book_in_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Book')),
            ],
        ),
    ]
