# Generated by Django 4.0.6 on 2022-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=121, upload_to='photo/user/%Y/%m/%d/', verbose_name='User photo'),
            preserve_default=False,
        ),
    ]
