# Generated by Django 4.0.6 on 2022-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/user/%Y/%m/%d/', verbose_name='User photo'),
        ),
    ]
