# Generated by Django 4.0.6 on 2022-11-29 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_of_the_book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='author_of_the_book',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='author_of_the_book',
            name='photo',
            field=models.ImageField(upload_to='photo/author/%Y/%m/%d/', verbose_name='Фотография автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.author_of_the_book', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre_of_the_book', verbose_name='Кагория книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='photo/book/%Y/%m/%d/', verbose_name='Фотография книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Названеи книги'),
        ),
        migrations.AlterField(
            model_name='comment_book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment_book',
            name='book_in_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='comment_book',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='genre_of_the_book',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='moderator',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/user/%Y/%m/%d/', verbose_name='Фото пользователя'),
        ),
    ]
