# Generated by Django 4.0.6 on 2023-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_author_of_the_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_book',
            name='is_publishe',
            field=models.BooleanField(default=True, verbose_name='Бубликация комметария'),
        ),
    ]
