# Generated by Django 4.0.6 on 2023-03-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_book_is_publishe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author_of_the_book',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='comment_book',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='genre_of_the_book',
            options={'verbose_name': 'Жанр книги', 'verbose_name_plural': 'Жанры книг'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.CreateModel(
            name='selection_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre_of_the_book', verbose_name='Кагория подборки')),
            ],
            options={
                'verbose_name': 'Подьорка книг',
                'verbose_name_plural': 'Подборки книг',
            },
        ),
    ]
