# Generated by Django 4.0.6 on 2023-03-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_book_news_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
